cli_settings:
  outputdir: D:\scripts\robot_framework_playground\Results
#  RPA
#  Name
#  Doc
#  Metadata
#  TestNames
#  TaskNames
#  SuiteNames
#  ParseInclude
#  SetTag
#  Include
#  Exclude
#  Log
#  Report
#  XUnit
#  SplitLog
#  TimestampOutputs
#  LogTitle
#  ReportTitle
#  ReportBackground
#  SuiteStatLevel
#  TagStatInclude
#  TagStatExclude
#  TagStatCombine
#  TagDoc
#  TagStatLink
#  RemoveKeywords
#  ExpandKeywords
#  FlattenKeywords
#  PreRebotModifiers
#  StatusRC
#  ConsoleColors
#  PythonPath
#  StdOut
#  StdErr
#  Extension
#  Output
#  LogLevel
#  MaxErrorLines
#  MaxAssignLength
#  DryRun
#  ExitOnFailure
#  ExitOnError
#  Skip
#  SkipOnFailure
#  SkipTeardownOnExit
#  ReRunFailed
#  ReRunFailedSuites
#  Randomize
#  RunEmptySuite
#  Variables
#  VariableFiles
#  Parsers
#  PreRunModifiers
#  Listeners
#  ConsoleType
#  ConsoleTypeDotted
#  ConsoleTypeQuiet
#  ConsoleWidth
#  ConsoleMarkers
#  DebugFile
#  Language
